let announcements = []; let schedules = [];
const IMAGE_BUCKET = 'notice-images';
function actionButton(text, className, handler) { const button = make('button', className, text); button.type = 'button'; button.addEventListener('click', handler); return button; }
function validateImage(file) { if (!file) return null; if (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024) return '이미지는 JPG, PNG, WEBP, GIF 형식의 5MB 이하 파일만 올릴 수 있습니다.'; return null; }
async function uploadImage(file, folder) { const errorMessage = validateImage(file); if (errorMessage) throw new Error(errorMessage); const name = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${folder}/${crypto.randomUUID()}-${name}`; const { error } = await supabaseClient.storage.from(IMAGE_BUCKET).upload(path, file, { cacheControl: '3600' }); if (error) throw error; return path; }
async function removeImage(path) { if (path) await supabaseClient.storage.from(IMAGE_BUCKET).remove([path]); }
function adminNotice(item) { const row = make('article', 'admin-row'); const info = make('div'); info.append(make('h3', '', item.title), make('p', 'muted', `${formatDateTime(item.created_at)}${item.is_important ? ' · 중요 공지' : ''}${item.image_path ? ' · 이미지 첨부됨' : ''}`)); const actions = make('div', 'row-actions'); actions.append(actionButton('수정', 'small-button', () => editNotice(item)), actionButton(item.is_important ? '고정 해제' : '중요 고정', 'small-button', () => toggleImportant(item)), actionButton('삭제', 'small-button danger', () => deleteNotice(item))); row.append(info, actions); return row; }
function adminSchedule(item) { const row = make('article', 'admin-row'); const info = make('div'); info.append(make('h3', '', item.title), make('p', 'muted', formatDate(item.event_date))); const actions = make('div', 'row-actions'); actions.append(actionButton('수정', 'small-button', () => editSchedule(item)), actionButton('삭제', 'small-button danger', () => deleteSchedule(item))); row.append(info, actions); return row; }
async function loadAdminData() { const [a, s] = await Promise.all([supabaseClient.from('announcements').select('*').order('created_at', { ascending: false }), supabaseClient.from('schedules').select('*').order('event_date')]); if (a.error || s.error) { $('#admin-error').textContent = '관리 목록을 불러오지 못했습니다. 관리자 권한을 확인해주세요.'; return; } announcements = a.data; schedules = s.data; const at = $('#admin-announcements'); const st = $('#admin-schedules'); at.replaceChildren(...announcements.map(adminNotice)); st.replaceChildren(...schedules.map(adminSchedule)); if (!announcements.length) renderEmpty(at, '등록된 공지가 없습니다.'); if (!schedules.length) renderEmpty(st, '등록된 일정이 없습니다.'); }
function showForm(id) { $(id).hidden = false; $(id).scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function hideForm(id) { const form = $(id); form.reset(); $('[name="id"]', form).value = ''; form.hidden = true; }
function editNotice(item) { const form = $('#announcement-form'); $('[name="id"]', form).value = item.id; $('[name="title"]', form).value = item.title; $('[name="content"]', form).value = item.content; $('[name="is_important"]', form).checked = item.is_important; showForm('#announcement-form'); }
function editSchedule(item) { const form = $('#schedule-form'); $('[name="id"]', form).value = item.id; $('[name="event_date"]', form).value = item.event_date; $('[name="title"]', form).value = item.title; $('[name="description"]', form).value = item.description || ''; showForm('#schedule-form'); }
async function toggleImportant(item) { const { error } = await supabaseClient.from('announcements').update({ is_important: !item.is_important }).eq('id', item.id); if (error) return showToast('중요 공지 설정을 변경하지 못했습니다.', true); showToast('중요 공지 설정을 변경했습니다.'); loadAdminData(); }
async function deleteNotice(item) { if (!confirm(`정말 '${item.title}' 공지를 삭제하시겠습니까?`)) return; const { error } = await supabaseClient.from('announcements').delete().eq('id', item.id); if (error) return showToast('공지를 삭제하지 못했습니다.', true); await removeImage(item.image_path); showToast('공지를 삭제했습니다.'); loadAdminData(); }
async function deleteSchedule(item) { if (!confirm(`정말 '${item.title}' 일정을 삭제하시겠습니까?`)) return; const { error } = await supabaseClient.from('schedules').delete().eq('id', item.id); if (error) return showToast('일정을 삭제하지 못했습니다.', true); showToast('일정을 삭제했습니다.'); loadAdminData(); }
async function saveNotice(event) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const id = data.get('id'); const oldItem = announcements.find(item => item.id === id); const file = data.get('image'); let imagePath = oldItem?.image_path || null; try { if (file?.size) imagePath = await uploadImage(file, 'announcements'); else if (data.get('remove_image') === 'on') imagePath = null; const payload = { title: data.get('title').trim(), content: data.get('content').trim(), is_important: data.get('is_important') === 'on', image_path: imagePath }; const query = id ? supabaseClient.from('announcements').update(payload).eq('id', id) : supabaseClient.from('announcements').insert(payload); const { error } = await query; if (error) throw error; if (oldItem?.image_path && oldItem.image_path !== imagePath) await removeImage(oldItem.image_path); hideForm('#announcement-form'); showToast('공지를 저장했습니다.'); loadAdminData(); } catch (error) { if (file?.size && imagePath !== oldItem?.image_path) await removeImage(imagePath); showToast(error.message || '공지 또는 이미지를 저장하지 못했습니다.', true); } }
async function saveSchedule(event) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const id = data.get('id'); const payload = { title: data.get('title').trim(), description: data.get('description').trim(), event_date: data.get('event_date') }; const query = id ? supabaseClient.from('schedules').update(payload).eq('id', id) : supabaseClient.from('schedules').insert(payload); const { error } = await query; if (error) return showToast('일정을 저장하지 못했습니다. 권한을 확인해주세요.', true); hideForm('#schedule-form'); showToast('일정을 저장했습니다.'); loadAdminData(); }
async function saveTimetable(event) { event.preventDefault(); const form = event.currentTarget; const file = new FormData(form).get('image'); let path; try { path = await uploadImage(file, 'timetable'); const { data: old } = await supabaseClient.from('timetable').select('image_path').eq('id', 1).maybeSingle(); const { error } = await supabaseClient.from('timetable').upsert({ id: 1, image_path: path, updated_at: new Date().toISOString() }); if (error) throw error; await removeImage(old?.image_path); form.reset(); showToast('시간표를 저장했습니다.'); } catch (error) { await removeImage(path); showToast(error.message || '시간표를 저장하지 못했습니다.', true); } }
document.addEventListener('DOMContentLoaded', async () => { if (!supabaseClient) { location.replace('login.html'); return; } const { data: { session } } = await supabaseClient.auth.getSession(); if (!session) { location.replace('login.html'); return; } const { data: profile, error: profileError } = await supabaseClient.from('admin_profiles').select('is_admin').eq('id', session.user.id).maybeSingle(); if (profileError || !profile?.is_admin) { await supabaseClient.auth.signOut(); location.replace('login.html'); return; } $('#logout-button').addEventListener('click', async () => { await supabaseClient.auth.signOut(); location.replace('login.html'); }); $('#new-announcement').addEventListener('click', () => showForm('#announcement-form')); $('#new-schedule').addEventListener('click', () => showForm('#schedule-form')); $('#announcement-form').addEventListener('submit', saveNotice); $('#schedule-form').addEventListener('submit', saveSchedule); $('#timetable-form').addEventListener('submit', saveTimetable); document.querySelectorAll('.cancel-edit').forEach(button => button.addEventListener('click', () => hideForm(`#${button.closest('form').id}`))); loadAdminData(); });
