let announcements = [], schedules = [], holidays = [];
const IMAGE_BUCKET = 'notice-images';
const button = (text, cls, fn) => { const el = make('button', cls, text); el.type = 'button'; el.addEventListener('click', fn); return el; };
function validateImage(file) { return !file || (file.type.startsWith('image/') && file.size <= 5 * 1024 * 1024) ? null : '이미지는 JPG, PNG, WEBP, GIF 형식의 5MB 이하 파일만 올릴 수 있습니다.'; }
async function uploadImage(file, folder) { const message = validateImage(file); if (message) throw new Error(message); const name = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${folder}/${crypto.randomUUID()}-${name}`; const { error } = await supabaseClient.storage.from(IMAGE_BUCKET).upload(path, file, { cacheControl: '3600' }); if (error) throw error; return path; }
async function removeImage(path) { if (path) await supabaseClient.storage.from(IMAGE_BUCKET).remove([path]); }
function hideForm(id) { const form = $(id); form.reset(); $('[name="id"]', form).value = ''; form.hidden = true; }
function showForm(id) { $(id).hidden = false; $(id).scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function listRow(item, type) { const date = type === 'holiday' ? item.holiday_date : item.event_date; const row = make('article', 'admin-row'), info = make('div'), actions = make('div', 'row-actions'); info.append(make('h3', '', item.title || item.name), make('p', 'muted', date ? formatDate(date) : `${formatDateTime(item.created_at)}${item.is_important ? ' · 중요 공지' : ''}${item.image_path ? ' · 이미지 첨부됨' : ''}`)); actions.append(button('수정', 'small-button', () => editItem(item, type)), button('삭제', 'small-button danger', () => deleteItem(item, type))); if (type === 'notice') actions.prepend(button(item.is_important ? '고정 해제' : '중요 고정', 'small-button', () => toggleImportant(item))); row.append(info, actions); return row; }
function editItem(item, type) { const form = $(`#${type === 'notice' ? 'announcement' : type}-form`); $('[name="id"]', form).value = item.id; if (type === 'notice') { $('[name="title"]', form).value = item.title; $('[name="content"]', form).value = item.content; $('[name="is_important"]', form).checked = item.is_important; } else { $('[name="title"]', form).value = item.title || ''; $('[name="name"]', form).value = item.name || ''; $(`[name="${type === 'holiday' ? 'holiday_date' : 'event_date'}"]`, form).value = type === 'holiday' ? item.holiday_date : item.event_date; if (type === 'schedule') $('[name="description"]', form).value = item.description || ''; } showForm(`#${form.id}`); }
async function loadAdminData() { const [a, s, h] = await Promise.all([supabaseClient.from('announcements').select('*').order('created_at', { ascending: false }), supabaseClient.from('schedules').select('*').order('event_date'), supabaseClient.from('holidays').select('*').order('holiday_date')]); if (a.error || s.error || h.error) return $('#admin-error').textContent = '관리 목록을 불러오지 못했습니다. 데이터베이스 설정과 권한을 확인해주세요.'; announcements = a.data; schedules = s.data; holidays = h.data; [['#admin-announcements', announcements, 'notice', '등록된 공지가 없습니다.'], ['#admin-schedules', schedules, 'schedule', '등록된 일정이 없습니다.'], ['#admin-holidays', holidays, 'holiday', '등록된 공휴일이 없습니다.']].forEach(([id, items, type, empty]) => { const target = $(id); target.replaceChildren(...items.map(item => listRow(item, type))); if (!items.length) renderEmpty(target, empty); }); }
async function toggleImportant(item) { const { error } = await supabaseClient.from('announcements').update({ is_important: !item.is_important }).eq('id', item.id); showToast(error ? '중요 공지 설정을 변경하지 못했습니다.' : '중요 공지 설정을 변경했습니다.', Boolean(error)); if (!error) loadAdminData(); }
async function deleteItem(item, type) { const table = type === 'notice' ? 'announcements' : type === 'holiday' ? 'holidays' : 'schedules'; if (!confirm(`정말 '${item.title || item.name}' 항목을 삭제하시겠습니까?`)) return; const { error } = await supabaseClient.from(table).delete().eq('id', item.id); if (error) return showToast('삭제하지 못했습니다.', true); if (type === 'notice') await removeImage(item.image_path); showToast('삭제했습니다.'); loadAdminData(); }
async function saveNotice(event) { event.preventDefault(); const form = event.currentTarget, data = new FormData(form), id = data.get('id'), old = announcements.find(item => item.id === id), file = data.get('image'); let imagePath = old?.image_path || null; try { if (file?.size) imagePath = await uploadImage(file, 'announcements'); else if (data.get('remove_image') === 'on') imagePath = null; const payload = { title: data.get('title').trim(), content: data.get('content').trim(), is_important: data.get('is_important') === 'on', image_path: imagePath }; const { error } = await (id ? supabaseClient.from('announcements').update(payload).eq('id', id) : supabaseClient.from('announcements').insert(payload)); if (error) throw error; if (old?.image_path !== imagePath) await removeImage(old?.image_path); hideForm('#announcement-form'); showToast('공지를 저장했습니다.'); loadAdminData(); } catch (error) { if (file?.size && imagePath !== old?.image_path) await removeImage(imagePath); showToast(error.message || '저장하지 못했습니다.', true); } }
async function saveSimple(event, type) { event.preventDefault(); const form = event.currentTarget, data = new FormData(form), id = data.get('id'); const table = type === 'holiday' ? 'holidays' : 'schedules'; const payload = type === 'holiday' ? { name: data.get('name').trim(), holiday_date: data.get('holiday_date') } : { title: data.get('title').trim(), description: data.get('description').trim(), event_date: data.get('event_date') }; const { error } = await (id ? supabaseClient.from(table).update(payload).eq('id', id) : supabaseClient.from(table).insert(payload)); if (error) return showToast('저장하지 못했습니다. 권한을 확인해주세요.', true); hideForm(`#${type}-form`); showToast('저장했습니다.'); loadAdminData(); }
async function saveImagePlan(event, table, folder, label) { event.preventDefault(); const form = event.currentTarget, file = new FormData(form).get('image'); let path; try { path = await uploadImage(file, folder); const { data: old } = await supabaseClient.from(table).select('image_path').eq('id', 1).maybeSingle(); const { error } = await supabaseClient.from(table).upsert({ id: 1, image_path: path, updated_at: new Date().toISOString() }); if (error) throw error; await removeImage(old?.image_path); form.reset(); showToast(`${label}를 저장했습니다.`); } catch (error) { await removeImage(path); showToast(error.message || `${label}를 저장하지 못했습니다.`, true); } }
document.addEventListener('DOMContentLoaded', async () => { if (!supabaseClient) return location.replace('login.html'); const { data: { session } } = await supabaseClient.auth.getSession(); if (!session) return location.replace('login.html'); const { data: profile } = await supabaseClient.from('admin_profiles').select('is_admin').eq('id', session.user.id).maybeSingle(); if (!profile?.is_admin) { await supabaseClient.auth.signOut(); return location.replace('login.html'); } $('#logout-button').addEventListener('click', async () => { await supabaseClient.auth.signOut(); location.replace('login.html'); }); [['#new-announcement', '#announcement-form'], ['#new-schedule', '#schedule-form'], ['#new-holiday', '#holiday-form']].forEach(([btn, form]) => $(btn).addEventListener('click', () => showForm(form))); $('#announcement-form').addEventListener('submit', saveNotice); $('#schedule-form').addEventListener('submit', event => saveSimple(event, 'schedule')); $('#holiday-form').addEventListener('submit', event => saveSimple(event, 'holiday')); $('#timetable-form').addEventListener('submit', event => saveImagePlan(event, 'timetable', 'timetable', '시간표')); $('#meal-form').addEventListener('submit', event => saveImagePlan(event, 'meal_plans', 'meal-plans', '급식표')); document.querySelectorAll('.cancel-edit').forEach(el => el.addEventListener('click', () => hideForm(`#${el.closest('form').id}`))); loadAdminData(); });
