let announcements = [], schedules = [];
const IMAGE_BUCKET = 'notice-images';
const action = (text, cls, fn) => { const el = make('button', cls, text); el.type = 'button'; el.onclick = fn; return el; };
function validateImage(file) { return !file || (file.type.startsWith('image/') && file.size <= 5242880) ? null : '이미지는 5MB 이하의 이미지 파일만 올릴 수 있습니다.'; }
async function uploadImage(file, folder) { const msg = validateImage(file); if (msg) throw new Error(msg); const path = `${folder}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '_')}`; const { error } = await supabaseClient.storage.from(IMAGE_BUCKET).upload(path, file, { cacheControl: '3600' }); if (error) throw error; return path; }
async function removeImage(path) { if (path) await supabaseClient.storage.from(IMAGE_BUCKET).remove([path]); }
function hideForm(id) { const form = $(id); form.reset(); $('[name="id"]', form).value = ''; form.hidden = true; }
function showForm(id) { $(id).hidden = false; $(id).scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function noticeRow(item) { const row = make('article', 'admin-row'), info = make('div'), actions = make('div', 'row-actions'); info.append(make('h3', '', item.title), make('p', 'muted', formatDateTime(item.created_at))); actions.append(action('수정', 'small-button', () => editNotice(item)), action(item.is_important ? '고정 해제' : '중요 고정', 'small-button', () => toggleImportant(item)), action('삭제', 'small-button danger', () => deleteNotice(item))); row.append(info, actions); return row; }
function scheduleRow(item) { const row = make('article', 'admin-row'), info = make('div'), actions = make('div', 'row-actions'); info.append(make('h3', '', item.title), make('p', 'muted', formatDate(item.event_date))); actions.append(action('수정', 'small-button', () => editSchedule(item)), action('삭제', 'small-button danger', () => deleteSchedule(item))); row.append(info, actions); return row; }
async function loadAdminData() { const [a, s] = await Promise.all([supabaseClient.from('announcements').select('*').order('created_at', { ascending: false }), supabaseClient.from('schedules').select('*').order('event_date')]); if (a.error || s.error) return $('#admin-error').textContent = '관리 목록을 불러오지 못했습니다. 권한을 확인해주세요.'; announcements = a.data; schedules = s.data; $('#admin-announcements').replaceChildren(...announcements.map(noticeRow)); $('#admin-schedules').replaceChildren(...schedules.map(scheduleRow)); if (!announcements.length) renderEmpty($('#admin-announcements'), '등록된 공지가 없습니다.'); if (!schedules.length) renderEmpty($('#admin-schedules'), '등록된 일정이 없습니다.'); }
function editNotice(item) { const form = $('#announcement-form'); $('[name="id"]', form).value = item.id; $('[name="title"]', form).value = item.title; $('[name="content"]', form).value = item.content; $('[name="is_important"]', form).checked = item.is_important; showForm('#announcement-form'); }
function editSchedule(item) { const form = $('#schedule-form'); $('[name="id"]', form).value = item.id; $('[name="event_date"]', form).value = item.event_date; $('[name="title"]', form).value = item.title; $('[name="description"]', form).value = item.description || ''; showForm('#schedule-form'); }
async function toggleImportant(item) { const { error } = await supabaseClient.from('announcements').update({ is_important: !item.is_important }).eq('id', item.id); showToast(error ? '변경하지 못했습니다.' : '변경했습니다.', Boolean(error)); if (!error) loadAdminData(); }
async function deleteNotice(item) { if (!confirm(`'${item.title}' 공지를 삭제할까요?`)) return; const { error } = await supabaseClient.from('announcements').delete().eq('id', item.id); if (!error) await removeImage(item.image_path); showToast(error ? '삭제하지 못했습니다.' : '삭제했습니다.', Boolean(error)); if (!error) loadAdminData(); }
async function deleteSchedule(item) { if (!confirm(`'${item.title}' 일정을 삭제할까요?`)) return; const { error } = await supabaseClient.from('schedules').delete().eq('id', item.id); showToast(error ? '삭제하지 못했습니다.' : '삭제했습니다.', Boolean(error)); if (!error) loadAdminData(); }
async function saveNotice(e) { e.preventDefault(); const form = e.currentTarget, data = new FormData(form), id = data.get('id'), old = announcements.find(x => x.id === id), file = data.get('image'); let imagePath = old?.image_path || null; try { if (file?.size) imagePath = await uploadImage(file, 'announcements'); else if (data.get('remove_image') === 'on') imagePath = null; const payload = { title: data.get('title').trim(), content: data.get('content').trim(), is_important: data.get('is_important') === 'on', image_path: imagePath }; const { error } = await (id ? supabaseClient.from('announcements').update(payload).eq('id', id) : supabaseClient.from('announcements').insert(payload)); if (error) throw error; if (old?.image_path !== imagePath) await removeImage(old?.image_path); hideForm('#announcement-form'); showToast('공지를 저장했습니다.'); loadAdminData(); } catch (error) { if (file?.size && imagePath !== old?.image_path) await removeImage(imagePath); showToast(error.message || '저장하지 못했습니다.', true); } }
async function saveSchedule(e) { e.preventDefault(); const form = e.currentTarget, d = new FormData(form), id = d.get('id'), payload = { title: d.get('title').trim(), description: d.get('description').trim(), event_date: d.get('event_date') }; const { error } = await (id ? supabaseClient.from('schedules').update(payload).eq('id', id) : supabaseClient.from('schedules').insert(payload)); showToast(error ? '저장하지 못했습니다.' : '일정을 저장했습니다.', Boolean(error)); if (!error) { hideForm('#schedule-form'); loadAdminData(); } }
async function savePlan(e, table, folder, label) { e.preventDefault(); const form = e.currentTarget; let path; try { path = await uploadImage(new FormData(form).get('image'), folder); const { data: old } = await supabaseClient.from(table).select('image_path').eq('id', 1).maybeSingle(); const { error } = await supabaseClient.from(table).upsert({ id: 1, image_path: path, updated_at: new Date().toISOString() }); if (error) throw error; await removeImage(old?.image_path); form.reset(); showToast(`${label}를 저장했습니다.`); } catch (error) { await removeImage(path); showToast(error.message || `${label}를 저장하지 못했습니다.`, true); } }
document.addEventListener('DOMContentLoaded', async () => { if (!supabaseClient) return location.replace('login.html'); const { data: { session } } = await supabaseClient.auth.getSession(); if (!session) return location.replace('login.html'); const { data: profile } = await supabaseClient.from('admin_profiles').select('is_admin').eq('id', session.user.id).maybeSingle(); if (!profile?.is_admin) { await supabaseClient.auth.signOut(); return location.replace('login.html'); } $('#logout-button').onclick = async () => { await supabaseClient.auth.signOut(); location.replace('login.html'); }; $('#new-announcement').onclick = () => showForm('#announcement-form'); $('#new-schedule').onclick = () => showForm('#schedule-form'); $('#announcement-form').onsubmit = saveNotice; $('#schedule-form').onsubmit = saveSchedule; $('#timetable-form').onsubmit = e => savePlan(e, 'timetable', 'timetable', '시간표'); $('#meal-form').onsubmit = e => savePlan(e, 'meal_plans', 'meal-plans', '급식표'); document.querySelectorAll('.cancel-edit').forEach(el => el.onclick = () => hideForm(`#${el.closest('form').id}`)); loadAdminData(); });
