let allSchedules = [];
let allHolidays = [];
let visibleMonth = new Date();
let selectedDate = new Date().toISOString().slice(0, 10);
const toDateKey = date => [date.getFullYear(), String(date.getMonth() + 1).padStart(2, '0'), String(date.getDate()).padStart(2, '0')].join('-');
const dateFromKey = key => new Date(`${key}T00:00:00`);
const holidaysForDate = key => allHolidays.filter(item => item.holiday_date === key);
function scheduleCard(item) { const article = make('article', `timeline-item${item.isHoliday ? ' holiday-item' : ''}`); article.append(make('h3', '', item.title)); if (item.description) article.append(make('p', 'excerpt', item.description)); return article; }
function renderSelectedDate() { const schedules = allSchedules.filter(item => item.event_date === selectedDate); const holidays = holidaysForDate(selectedDate).map(item => ({ title: item.name, description: '공휴일', isHoliday: true })); const items = [...holidays, ...schedules]; $('#selected-date-title').textContent = formatDate(selectedDate); const target = $('#selected-schedule-list'); target.replaceChildren(...items.map(scheduleCard)); if (!items.length) renderEmpty(target, '등록된 일정이 없습니다.'); }
function renderCalendar() { const grid = $('#calendar-grid'); const year = visibleMonth.getFullYear(); const month = visibleMonth.getMonth(); $('#calendar-title').textContent = `${year}년 ${month + 1}월`; grid.replaceChildren(); const firstWeekday = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); const todayKey = toDateKey(new Date()); for (let i = 0; i < firstWeekday; i += 1) grid.append(make('div', 'calendar-blank')); for (let day = 1; day <= daysInMonth; day += 1) { const key = toDateKey(new Date(year, month, day)); const schedules = allSchedules.filter(item => item.event_date === key); const holidays = holidaysForDate(key); const button = make('button', 'calendar-day', String(day)); button.type = 'button'; button.classList.toggle('today', key === todayKey); button.classList.toggle('selected', key === selectedDate); button.classList.toggle('has-event', schedules.length > 0); button.classList.toggle('holiday', holidays.length > 0); button.setAttribute('aria-label', `${formatDate(key)}${holidays.length ? `, 공휴일 ${holidays.map(item => item.name).join(', ')}` : ''}${schedules.length ? `, 일정 ${schedules.length}개` : ''}`); if (schedules.length) button.append(make('span', 'event-count', String(schedules.length))); button.addEventListener('click', () => { selectedDate = key; renderCalendar(); renderSelectedDate(); }); grid.append(button); } }
async function loadSchedules() { const target = $('#selected-schedule-list'); renderLoading(target); if (!supabaseClient) return displayError(target, connectionMessage()); const [scheduleResult, holidayResult] = await Promise.all([supabaseClient.from('schedules').select('*').order('event_date'), supabaseClient.from('holidays').select('*').order('holiday_date')]); if (scheduleResult.error || holidayResult.error) return displayError(target, '일정 또는 공휴일을 불러오지 못했습니다. 설정을 확인해주세요.'); allSchedules = scheduleResult.data; allHolidays = holidayResult.data; const firstUpcoming = [...allSchedules.map(item => item.event_date), ...allHolidays.map(item => item.holiday_date)].filter(key => key >= selectedDate).sort()[0]; if (firstUpcoming && !allSchedules.some(item => item.event_date === selectedDate) && !allHolidays.some(item => item.holiday_date === selectedDate)) { selectedDate = firstUpcoming; visibleMonth = dateFromKey(selectedDate); } renderCalendar(); renderSelectedDate(); }
document.addEventListener('DOMContentLoaded', () => { $('#previous-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1); renderCalendar(); }); $('#next-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1); renderCalendar(); }); loadSchedules(); });
