let allSchedules = [];
let visibleMonth = new Date();
let selectedDate = new Date().toISOString().slice(0, 10);
const toDateKey = date => [date.getFullYear(), String(date.getMonth() + 1).padStart(2, '0'), String(date.getDate()).padStart(2, '0')].join('-');
const dateFromKey = key => new Date(`${key}T00:00:00`);
const holidayNamePattern = /(공휴일|대체s*공휴일|신정|설날|삼일절|3·1절|어린이날|부처님오신날|석가탄신일|현충일|광복절|개천절|한글날|크리스마스|성탄절)/;
const isHoliday = item => holidayNamePattern.test(`${item.title || ''} ${item.description || ''}`);
function scheduleCard(item) { const article = make('article', `timeline-item${isHoliday(item) ? ' holiday-item' : ''}`); article.append(make('h3', '', item.title)); if (item.description) article.append(make('p', 'excerpt', item.description)); return article; }
function renderSelectedDate() { const items = allSchedules.filter(item => item.event_date === selectedDate); $('#selected-date-title').textContent = formatDate(selectedDate); const target = $('#selected-schedule-list'); target.replaceChildren(...items.map(scheduleCard)); if (!items.length) renderEmpty(target, '등록된 일정이 없습니다.'); }
function renderCalendar() { const grid = $('#calendar-grid'); const year = visibleMonth.getFullYear(); const month = visibleMonth.getMonth(); $('#calendar-title').textContent = `${year}년 ${month + 1}월`; grid.replaceChildren(); const firstWeekday = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); const todayKey = toDateKey(new Date()); for (let i = 0; i < firstWeekday; i += 1) grid.append(make('div', 'calendar-blank')); for (let day = 1; day <= daysInMonth; day += 1) { const key = toDateKey(new Date(year, month, day)); const items = allSchedules.filter(item => item.event_date === key); const button = make('button', 'calendar-day', String(day)); button.type = 'button'; button.classList.toggle('today', key === todayKey); button.classList.toggle('selected', key === selectedDate); button.classList.toggle('has-event', items.length > 0); button.classList.toggle('holiday', items.some(isHoliday)); button.setAttribute('aria-label', `${formatDate(key)}${items.length ? `, 일정 ${items.length}개` : ''}`); if (items.length) button.append(make('span', 'event-count', String(items.length))); button.addEventListener('click', () => { selectedDate = key; renderCalendar(); renderSelectedDate(); }); grid.append(button); } }
async function loadSchedules() { const target = $('#selected-schedule-list'); renderLoading(target); if (!supabaseClient) return displayError(target, connectionMessage()); const { data, error } = await supabaseClient.from('schedules').select('*').order('event_date'); if (error) return displayError(target, '일정을 불러오지 못했습니다. 잠시 후 다시 시도해주세요.'); allSchedules = data; const firstUpcoming = data.find(item => item.event_date >= selectedDate); if (firstUpcoming && !data.some(item => item.event_date === selectedDate)) { selectedDate = firstUpcoming.event_date; visibleMonth = dateFromKey(selectedDate); } renderCalendar(); renderSelectedDate(); }
document.addEventListener('DOMContentLoaded', () => { $('#previous-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1); renderCalendar(); }); $('#next-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1); renderCalendar(); }); loadSchedules(); });
