let allSchedules = [];
let visibleMonth = new Date();
let selectedDate = new Date().toISOString().slice(0, 10);
const toDateKey = date => [date.getFullYear(), String(date.getMonth() + 1).padStart(2, '0'), String(date.getDate()).padStart(2, '0')].join('-');
const dateFromKey = key => new Date(`${key}T00:00:00`);
// 사용자가 제공한 2026년 달력 기준: 8~12월 법정공휴일입니다.
const RED_HOLIDAY_DATES = new Set(['2026-08-15', '2026-09-24', '2026-09-25', '2026-09-26', '2026-10-03', '2026-10-05', '2026-10-09', '2026-12-25']);
const isRedDay = (key, date) => date.getDay() === 0 || RED_HOLIDAY_DATES.has(key);
function scheduleCard(item) { const article = make('article', 'timeline-item'); article.append(make('h3', '', item.title)); if (item.description) article.append(make('p', 'excerpt', item.description)); return article; }
function renderSelectedDate() { const items = allSchedules.filter(item => item.event_date === selectedDate); $('#selected-date-title').textContent = formatDate(selectedDate); const target = $('#selected-schedule-list'); target.replaceChildren(...items.map(scheduleCard)); if (!items.length) renderEmpty(target, '등록된 일정이 없습니다.'); }
function renderCalendar() { const grid = $('#calendar-grid'); const year = visibleMonth.getFullYear(); const month = visibleMonth.getMonth(); $('#calendar-title').textContent = `${year}년 ${month + 1}월`; grid.replaceChildren(); const firstWeekday = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); const todayKey = toDateKey(new Date()); for (let i = 0; i < firstWeekday; i += 1) grid.append(make('div', 'calendar-blank')); for (let day = 1; day <= daysInMonth; day += 1) { const date = new Date(year, month, day); const key = toDateKey(date); const items = allSchedules.filter(item => item.event_date === key); const button = make('button', 'calendar-day', String(day)); button.type = 'button'; button.classList.toggle('today', key === todayKey); button.classList.toggle('selected', key === selectedDate); button.classList.toggle('has-event', items.length > 0); button.classList.toggle('holiday', isRedDay(key, date)); button.setAttribute('aria-label', `${formatDate(key)}${items.length ? `, 일정 ${items.length}개` : ''}`); if (items.length) button.append(make('span', 'event-count', String(items.length))); button.addEventListener('click', () => { selectedDate = key; renderCalendar(); renderSelectedDate(); }); grid.append(button); } }
async function loadSchedules() { const target = $('#selected-schedule-list'); renderLoading(target); if (!supabaseClient) return displayError(target, connectionMessage()); const { data, error } = await supabaseClient.from('schedules').select('*').order('event_date'); if (error) return displayError(target, '일정을 불러오지 못했습니다. 잠시 후 다시 시도해주세요.'); allSchedules = data; const firstUpcoming = data.find(item => item.event_date >= selectedDate); if (firstUpcoming && !data.some(item => item.event_date === selectedDate)) { selectedDate = firstUpcoming.event_date; visibleMonth = dateFromKey(selectedDate); } renderCalendar(); renderSelectedDate(); }
document.addEventListener('DOMContentLoaded', () => { $('#previous-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1); renderCalendar(); }); $('#next-month').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1); renderCalendar(); }); loadSchedules(); });
